-- Liquibase SQL Changeset for Author table

-- Create Author table
CREATE TABLE author (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    document_ids JSONB NOT NULL,
    role VARCHAR(50) NOT NULL
);

CREATE INDEX idx_author_username ON author(username);