-- Liquibase SQL Changeset for Document table

-- Create Document table
CREATE TABLE document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    author_id BIGINT, -- Foreign key to Author
    reference_ids JSONB,
    CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES author(id) ON DELETE SET NULL
);